import { MapPin, Calendar, Building2, Clock, QrCode, Coffee, AlertCircle } from 'lucide-react';

/* ─── Shared SectionCard ─── */
function SectionCard({ title, icon: Icon, iconBg = 'bg-royal/5', iconColor = 'text-royal', children }) {
  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-[0_2px_12px_rgba(0,0,0,0.04)]">
      <div className="flex items-center gap-3 px-7 py-5 border-b border-gray-100">
        <div className={`w-9 h-9 rounded-xl ${iconBg} flex items-center justify-center`}>
          <Icon size={18} className={iconColor} />
        </div>
        <h2 className="text-base font-extrabold text-dark">{title}</h2>
      </div>
      <div className="px-7 py-6">{children}</div>
    </div>
  );
}

function QRCard({ label, color }) {
  return (
    <div className={`flex flex-col items-center gap-3 p-5 rounded-xl border ${color}`}>
      <QrCode size={64} className="opacity-60" />
      <p className="text-xs font-bold uppercase tracking-wide">{label}</p>
      <p className="text-[10px] text-gray-400 text-center">(QR will be generated by organizer)</p>
    </div>
  );
}

function MealBadge({ label, status }) {
  const collected = status === 'collected';
  return (
    <div className={`flex items-center gap-2 px-4 py-2.5 rounded-xl border text-sm font-semibold ${collected ? 'bg-emerald-50 border-emerald-100 text-emerald-700' : 'bg-gray-50 border-gray-100 text-gray-500'}`}>
      <Coffee size={14} />
      {label}:{' '}
      <span className={`font-bold ${collected ? 'text-emerald-700' : 'text-gray-400'}`}>
        {collected ? 'Collected' : 'Pending'}
      </span>
    </div>
  );
}

/* ─────────────────────── OFFLINE EVENT SECTION ─────────────
  Props:
    event: {
      workspaceNumber: string,
      entryQR: string | null,
      mealQR: string | null,
      lunchStatus: 'collected' | 'pending',
      dinnerStatus: 'collected' | 'pending',
      eventDate: string,
      venue: string,
      reportingTime: string,
      eventTimeline: [{ time, activity }]
    }
─────────────────────────────────────────────────────────── */
export default function OfflineEventSection({ event }) {
  return (
    <SectionCard title="Offline Event" icon={MapPin} iconBg="bg-violet-50" iconColor="text-violet-600">

      {/* Workspace + Timing Info */}
      <div className="grid sm:grid-cols-2 gap-4 mb-6">
        {[
          { icon: MapPin,    label: 'Workspace',  value: event.workspaceNumber },
          { icon: Calendar,  label: 'Date',       value: event.eventDate       },
          { icon: Building2, label: 'Venue',      value: event.venue           },
          { icon: Clock,     label: 'Report At',  value: event.reportingTime   },
        ].map(({ icon: Icon, label, value }) => (
          <div key={label} className="flex items-start gap-3 p-4 rounded-xl bg-light-gray">
            <Icon size={15} className="text-royal mt-0.5 shrink-0" />
            <div>
              <p className="text-[11px] font-bold text-gray-400 uppercase tracking-wide">{label}</p>
              <p className="text-sm font-bold text-dark mt-0.5">{value}</p>
            </div>
          </div>
        ))}
      </div>

      {/* QR Codes */}
      <div className="grid sm:grid-cols-2 gap-4 mb-6">
        <QRCard label="Gate Entry QR" color="bg-royal/5 border-royal/20 text-royal" />
        <QRCard label="Meal QR"       color="bg-emerald-50 border-emerald-100 text-emerald-700" />
      </div>

      {/* Meal Status */}
      <div className="flex flex-wrap gap-3 mb-6">
        <MealBadge label="Lunch"  status={event.lunchStatus}  />
        <MealBadge label="Dinner" status={event.dinnerStatus} />
      </div>

      {/* Event Timeline */}
      <div>
        <p className="text-xs font-bold text-gray-500 uppercase tracking-widest mb-4">Event Schedule</p>
        <div className="space-y-3">
          {event.eventTimeline.map((t, i) => (
            <div key={i} className="flex items-center gap-4">
              <span className="text-xs font-mono font-bold text-gray-400 w-16 shrink-0">{t.time}</span>
              <div className="w-2 h-2 rounded-full bg-royal/30 shrink-0" />
              <span className="text-sm text-gray-700 font-medium">{t.activity}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Note */}
      <div className="mt-6 flex items-start gap-3 p-4 rounded-xl bg-amber-50 border border-amber-100">
        <AlertCircle size={15} className="text-amber-500 shrink-0 mt-0.5" />
        <p className="text-sm text-amber-800">Carry original College ID. QR codes are required for entry and meals.</p>
      </div>
    </SectionCard>
  );
}
